# Generated by Django 4.1 on 2022-10-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_managers_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('shipped', 'Shipped'), ('refund', 'Refund'), ('delivered', 'Delivered'), ('created', 'Created')], default='created', max_length=20),
        ),
    ]
