# Generated by Django 4.1 on 2022-10-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('refund', 'Refund'), ('delivered', 'Delivered'), ('created', 'Created'), ('paid', 'Paid')], default='created', max_length=20),
        ),
    ]
