# Generated by Django 4.1 on 2022-10-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('delivered', 'Delivered'), ('shipped', 'Shipped'), ('refund', 'Refund'), ('paid', 'Paid')], default='created', max_length=20),
        ),
    ]
