# Generated by Django 4.1 on 2022-10-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('created', 'Created'), ('shipped', 'Shipped'), ('paid', 'Paid'), ('refund', 'Refund')], default='created', max_length=20),
        ),
    ]
