# Generated by Django 4.1 on 2022-10-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('paid', 'Paid'), ('delivered', 'Delivered'), ('refund', 'Refund'), ('created', 'Created')], default='created', max_length=20),
        ),
    ]
