# Generated by Django 4.1 on 2022-10-20 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
    ]
