# Generated by Django 4.1.1 on 2022-09-22 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['post_date']},
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='content',
        ),
    ]
