# Generated by Django 4.1.1 on 2022-09-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_alter_post_author_delete_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='what are your thoughts?', max_length=1000),
        ),
    ]
